### ISSUE TITLE
[URGENT] scan pdf in for patient document

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#283]
Please create button for user to be able to scan in a document from a scanner or attach a file from pc to a patient profile in the documents tab. A button there call attach file (and then user select weather from scanner or from computer) and then has to name it something.

![image](https://user-images.githubusercontent.com/61169385/100891044-dcd2da00-3486-11eb-9f94-8e9401850888.png)

**Comment by pwang-boxlabs** [comment]
hmm not sure if we really want that. The ideas is to get users to do all the documentation through our app. the ODB tool isn't possible otherwise because we can't identify which fields are entered if we add this feature. This is the only way we can advertise ourselves saying all (well most to be conservative) documents submitted in our app are valid.

**Comment by mikedemian** [comment]
This wouldn’t be used for that. It would be used for (as example) - lab test results
